### ISSUE TITLE
Plugin breaks Layouts on site generation.

### ISSUE THREAD

**Issue by neilkakkar** [keithmifsud/jekyll-target-blank#28] opened 2018-11-12 21:21 UTC
The entire body gets encapsulated in the header tag for my website. Not sure why.

__Development Tasks:__

- [x] Prepare tests stubs which must include `_layouts` as I believe the issue occurs on the first included layout.
- [x] Write tests and code for the tests to pass.
- [x] Refactor and re-test.
- [x] Write more stubs to match OPs scenario.
- [x] Once all tests pass, refactor for release.
- [ ] Push to pre-release branch
- [x] Publish a release on GH for v.1.1.1-beta
- [ ] Publish on RG and ask OP for test/review.
- [ ] Action any feedback
- [ ] Finalise for a stable release.
- [ ] Action release of v.1.1.1

**Comment by neilkakkar** [comment] 2018-11-13 07:04
Oh that's weird. Sure - here's the repo. I commented out the bit about the anchor - so try uncommenting it and running it.
https://github.com/neilkakkar/neilkakkar.com

Thanks!

**Comment by keithmifsud** [comment] 2018-11-27 00:34
Hi, @neilkakkar Thank you for fixing the quotes issues. This helps me to reduce possible errors and thus debug properly. The quotes do matter because Jekyll and JTB need to parse the source files and the quotes give meaning to the contained strings. I've now managed to reproduce the bug on your website and will attempt to write tests and reproduce it in the code for fixing. Hold tight 😄

**Comment by neilkakkar** [comment] 2018-11-27 06:29
Ah, great! I see, thanks!

**Comment by keithmifsud** [comment] 2018-12-11 02:20
@neilkakkar This issue seems to be with your HTML code. I cannot check all the site but I can already see you have an extra closing div `</div` in your footer file:

```html
<footer class="site-footer h-card">
  <data class="u-url" href="{{ '/' | relative_url }}"></data>

  <div class="wrapper">
    <!--<h2 class="footer-heading">{{ site.title | escape }}</h2> -->
    <div class="wrapper">
      {%- if page.no-footer-form != true -%}
        {%- include signup-form.html -%}
        <hr><br>
      {%- endif -%}

    </div> 
     
     <div class="footer-col-wrapper">
      <div class="footer-col footer-col-1">
        <ul class="contact-list">
          <li class="p-name">
            {%- if site.author -%}
              {{ site.author | escape }}
            {%- else -%}
              {{ site.title | escape }}
            {%- endif -%}
            </li>
          <li>
            {%- if site.subtitle -%}
              {{- site.subtitle | escape -}}
            {%- endif -%}
          </li>
            {%- if site.email -%}
            <li><a class="u-email" href="mailto:{{ site.email }}">{{ site.email }}</a></li>
            {%- endif -%}
        </ul>
      </div>

      <div class="footer-col footer-col-2">
        {%- include social.html -%}
      </div>

      <div class="footer-col footer-col-3">
        <p>{{- site.description | escape -}}</p>
      </div>
    </div> <!--- THIS IS EXTRA -->

  </div>

</footer>
```

**Comment by neilkakkar** [comment] 2018-12-11 19:58
Hey Keith, it isn't extra. The HTML is sound.  If I get some time during this christmas vacation, I'd dive into your code to figure out what's going wrong. Could be something non obvious on my end.

**Comment by Fenzland** [comment] 2018-12-16 07:51
#29 will help this

**Comment by keithmifsud** [comment] 2018-12-24 15:55
Thank you so much @Fenzland .. I linked you on twitter :) @neilkakkar .. please let us know if you have other issues. Happy Xmas to all!

**Closed by keithmifsud** 2018-12-24 15:55 UTC
Labels: bug
